### PR TITLE
Fix #265 - Add support for specifying port in .npmbuildrc

### LINKED ISSUE #265: Allow developer to specify port for webpack
https://github.com/liferay/liferay-npm-build-tools/blob/develop/packages/liferay-npm-build-support/src/resources/start/webpack.config.js.ejs

Add support for port specification in devServer options

### PR DESCRIPTION
**Pull request by travisrcory**

### CODE REVIEW

**Comment by izaera** [comment]
Just started reviewing :)

**Comment by izaera** [comment]
@travisrcory PRs must be sent to branch `develop` because `master` always reflects the latest released version. I will take of it anyway :+1:

**Comment by travisrcory** [comment]
giphy

**Comment by izaera** [comment]
Resent as https://github.com/liferay/liferay-npm-build-tools/pull/269. I'm closing.

**Pull request closed without merging**
