### PR TITLE
Don't remove trailing .js from package names

### PR DESCRIPTION
**Pull request by izaera**

### CODE REVIEW

**Comment by izaera** [comment]
This is the continuation of https://github.com/liferay/liferay-npm-build-tools/pull/11

**Comment by yuchi** [comment]
The PR name now doesn't reflect the changes (since it actually solves the issue!)

This is a better approach, but still not complete. See discussion on #11

**Comment by jbalsas** [comment]
I'm merging for now since @yuchi said this is at least a better approach... 

Couldn't we normalize in the loader on require-time?

**Comment by izaera** [comment]
@yuchi @jbalsas Please continue the discussions about this topic in this issue https://github.com/liferay/liferay-npm-build-tools/issues/14

thx :-)

**Pull request merged**
